'use strict';
/* exported LOGO_SVG */
// Generated by scripts/make-icons.js (npm run icons). Do not edit by hand.
const LOGO_SVG = '<svg class="brand-svg" viewBox="8 8 84 84" aria-hidden="true"><g transform="translate(22.769 30.462) scale(1.026)"><path d="M0 0L0 36M0 0L12 0M12 0A9 9 0 0 1 12 18M12 18L0 18M0 18L13.5 18M13.5 18A9 9 0 0 1 13.5 36M13.5 36L0 36M33 0L33 36M33 0L42 0M42 0A9 9 0 0 1 42 18M42 18L33 18M40 18L49.5 33.5" fill="none" stroke="#f4f5f7" stroke-width="5.4" stroke-linecap="round" stroke-linejoin="round"/><circle class="brand-dot" cx="51" cy="36" r="4.8" fill="#ff3b30"/></g></svg>';
